theme: jekyll-theme-slate

title: Combining Deep Learning and Verification for Precise Object Instance Detection

show_downloads: false

logo: https://github.com/jnan1/FlowVerify/blob/master/overview.png
